name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          version: 'latest'
          service_account_email: ${{ secrets.SERVICE_ACCOUNT }}
          service_account_key: ${{ secrets.CREDENTIALS }}
          export_default_credentials: true

      - name: Configure Docker
        id: docker
        run: |
          gcloud auth configure-docker

      - name: Build and Push Container
        run: |
          docker build -t "gcr.io/${{ secrets.PROJECT_ID }}/task-analytics:${{ github.sha }}" ./
          docker push "gcr.io/${{ secrets.PROJECT_ID }}/task-analytics:${{ github.sha }}"

      - name: Deploy to Cloud Run
        id: deploy
        run: |
          gcloud run deploy task-analytics \
          --region europe-west1 \
          --image gcr.io/${{ secrets.PROJECT_ID }}/task-analytics \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.PROJECT_ID }}

